//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_MVC.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVEntities : DbContext
    {
        public DbCVEntities()
            : base("name=DbCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
        public virtual DbSet<TBLCERTIFICATES> TBLCERTIFICATES { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACT { get; set; }
        public virtual DbSet<TBLEDUCATION> TBLEDUCATION { get; set; }
        public virtual DbSet<TBLEXPERIENCE> TBLEXPERIENCE { get; set; }
        public virtual DbSet<TBLHOBBY> TBLHOBBY { get; set; }
        public virtual DbSet<TBLSKILL> TBLSKILL { get; set; }
        public virtual DbSet<TBLABOUT> TBLABOUT { get; set; }
    }
}
